- name: nginx install and run
  hosts: local
  become: yes
  tass:
  - name: install nginx server
    ansible.builtin.package:
     name: nginx
     state: present
  - name: start nginx
    ansible.builtin.service:
     name: mginx
     state: enable
     enable: yes