- name : play with variables
  hosts: local
  connection: local
  vars:
    Number : 78

  tasks:
   - name : if the number is lessthan 100
     ansible.builtin.debug:
      msg: "Given number is {{Number}}"
     when:Number < 100