- name : play with variables
  hosts: local
  connection: local
  vars_prompt:
   - name : USERNAME
     prompt : enter the USERNAME
     private : true
  tasks:
   - name : print course information
     ansible.builtin.debug:
     msg: "Hello {{USERNAME}}"