- name : play with variables
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
     name: "{{item.name}}"
     state: "{{item.state}}"
    loop:
     - {name : 'nginx', state: 'present'}
     - {name : 'mysql', state: 'absent'}